shared:
  secret_key_base: goride
  role_member: MEMBER
  role_driver: DRIVER

development:

test:

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  role_member: <%= ENV["ROLE_MEMBER"] %>
  role_driver: <%= ENV["ROLE_DRIVER"] %>